### ISSUE TITLE
Failed at the node-sass@1.2.3 postinstall script

### ISSUE THREAD

**Issue by givanse** [M-Porter/ember-slim-boilerplate#1]
I stumbled upon this: https://github.com/sass/node-sass/issues/550 when trying to run the app.

Either removing  `broccoli-sass` or bumping the version to v0.6.0 fixes the problem.

Since this is a boilerplate app, I would remove the `broccoli-sass`. I believe that boilerplate code should use library defaults for everything so that new projects can be built out of them.

**Comment by M-Porter** [comment]
I like the idea of bumping the version to v0.6.0.

I honestly made this library for my own purpose never thinking that anyone else would ever use it haha.

If you think it would be a better idea not to use `broccoli-sass` then I am all for it.

**Comment by givanse** [comment]
Commit aef33b832f0602353babb985ac4c3d0c9b0588f7 bumped it.
